name: tripupnow
description: A travel planning and exploration mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^16.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  
  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  
  # Location & Maps
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.6.1
  
  # Utils
  intl: ^0.20.2
  url_launcher: ^6.2.6
  image_picker: ^1.1.2
  
  # Authentication
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700